window.DATA = {
    research: [
        "Don’t use your phone in a dark room. Don’t put your phone too close to your face. Don’t use your phone while walking. I’m sure your parents have said this to you before, or you may have said it to someone else before. But what if I were to tell you that there is something that throws all these guidelines to the sidelines, an item that is an inch from your eyes, sealed to allow no light in, and requires vigorous movements and even walking to operate.",
        "Virtual reality may seem like a sophisticated new technology, but it only gained widespread recognition after the success of the Oculus Rift in 2013. Before that, virtual reality was just an idea that was too ahead of its time. The concept of virtual reality originated in the 1930s with the book “Pygmalion’s Spectacles” by science fiction writer Stanley G. Weinbaum. However, the first virtual reality headset was not created until 20 years later, in the 1950s, utilising large and bulky CRT (Cathode Ray Tube) displays. Virtual reality has come a long way, now using state-of-the-art retina-level OLED (Organic Light-Emitting Diode) displays. The ability to interact with that virtual world had also vastly improved, being able to not only see and hear, but even feel using a multitude of different methods, using controllers, treadmills, hand and leg tracking, even eye and mouth tracking. But on top of all that, the sensory experience has improved leaps and bounds, too, now being able to see, hear, and even feel and smell through new technology like haptic feedback or electric stimulation. However, with all these new advancements, it only makes turning this virtual world into your main one more enticing.",
        "Now you may think, what’s wrong with having a little fun? It’s just another way of entertaining ourselves. And you are right. But don’t you know? Social media addiction, gaming addictions, brain rot. Virtual reality is precisely that, wait, never mind, it’s not. It’s worse. Now, not only are you just sitting and using your computer at a desk, or using your phone on your bed, you are isolating yourself from the world, unable to even tell the time, too distracted to realise you’re hungry, too engaged with virtual characters to talk to real people. And that is the first of many problems with virtual reality. Addiction. A seemingly common problem with any new technology these days, and the root of many of the other problems listed later. Virtual reality brings the seven deadly sins straight to your doorstep, letting you do whatever you want with your own hands, without any repercussions. But what are the practical effects of addiction?",
        "Let’s start with the social problems. By becoming addicted to this virtual world, real life can become dull after slaying dragons, talking to family members can feel like a chore after talking to the president, and this can cause people to isolate themselves in this virtual world, as it seems like the only one worth living in. This might cause people to withdraw and stop interacting with others in real life, or lead to a change in character as their role-playing becomes too extreme. But it’s not all bad. Virtual reality can also be a valuable and helpful tool. It has been used in prisons for rehabilitation, hospitals for surgery training or physical therapy, and even at home by people who suffer from mutism, using social games like VRChat to learn how to interact with others. After talking about mentally, what about physically? At the start of this [insert name of deliverable], I listed out the things your parents always tell you or what you may always tell others what not to do. Since virtual reality headsets contradict many of those guidelines, do they really impact your health? Generally speaking, excessive screen time can cause dry eyes and headaches. While irritating, this typically doesn't cause lasting harm or damage to your vision in the long term. This is also true for what we currently know about the blue light emitted from screens; it may disrupt your sleep, but research so far hasn't shown it's enough to damage your vision or have a negative impact on eye health. Based on recent studies, virtual reality also does not cause any adverse long-term effects on a child’s cognitive or visual abilities, with effects similar to those of typical devices.",
        "Finally, what about the economic impact of this industry? Unbeknownst to most, one of the largest virtual reality companies, Meta, has lost a staggering S$94.3 billion since launching its virtual reality department. Despite the apparent success of virtual reality headsets like the PSVR, paving the way for a successor, the PSVR2, as well as well-received headsets like the big screen beyond two and its prequel, the virtual reality market has not exactly been very profitable. Despite this, big players like Apple, Google and Samsung have been hard at work, haemorrhaging money to develop new groundbreaking headsets like the Apple Vision Pro and Galaxy XR (Previously known as Project Moohan), pushing the limits of what’s possible. Pimax, an independent virtual reality headset producer based in Shanghai, has also raised S$16.79 million from investors, along with other bullish trends from investors, thus proving that, despite the grim signs, many still believe that virtual reality is not a lost cause.",
        "All in all, virtual reality is a new and rapidly evolving technology with a past longer than expected, just like Artificial Intelligence. And that’s not the only similarity between them; both are also industries haemorrhaging money, and both are scrutinised by some to be a bubble. These two industries share a lot in common. And just like the AI industry, I believe that virtual reality will have its time to shine again. With the rise of augmented reality, because of shifts from major companies like Meta and Google, it is likely that virtual reality may not be in the spotlight, but that does not mean it is dead. Despite its various shortcomings, virtual reality also offers a plethora of benefits that can be reaped. But until the day NerveGear becomes real, I doubt it will ever be in the spotlight of our ever-changing and ever-evolving world again."
    ],
    sources: [
        { text: "BCC Research. (n.d.). <i>The history and evolution of virtual reality technology</i>.", link: "https://blog.bccresearch.com/the-history-and-evolution-of-virtual-reality-technology" },
        { text: "Skarbez, R., Smith, M., & Whitton, M. C. (2021). Revisiting Milgram and Kishino's Reality-Virtuality Continuum. <i>Frontiers in Virtual Reality, 2</i>.", link: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9517547/" },
        { text: "TechRadar. (2016). <i>Forgotten genius: The man who made a working VR machine in 1957</i>.", link: "https://www.techradar.com/news/wearables/forgotten-genius-the-man-who-made-a-working-vr-machine-in-1957-1318253/2" },
        { text: "YouTube. (n.d.). <i>[Video title unavailable]</i>.", link: "https://www.youtube.com/watch?v=UW8NapTA9o" },
        { text: "The Guardian. (2025, March 8). <i>VR prison California</i>.", link: "https://www.theguardian.com/technology/2025/mar/08/vr-prison-california" },
        { text: "Information Technology and Innovation Foundation. (2025, June 2). <i>AR/VR's potential in health care</i>.", link: "https://itif.org/publications/2025/06/02/arvrs-potential-in-health-care/" },
        { text: "CNET. (n.d.). <i>Is VR bad for your eyes? Here's what eye doctors say</i>.", link: "https://www.cnet.com/health/medical/is-vr-bad-for-your-eyes-heres-what-eye-doctors-say/" },
        { text: "Frontiers in Virtual Reality. (2025). <i>Article Title from Volume 10.3389</i>.", link: "https://www.frontiersin.org/journals/virtual-reality/articles/10.3389/frvir.2025.1547198/full" },
        { text: "Yahoo Finance. (n.d.). <i>Meta Platforms lost $73 billion</i>.", link: "https://finance.yahoo.com/news/meta-platforms-lost-73-billion-165823364.html" },
        { text: "Road to VR. (n.d.). <i>Pimax raises $13m to accelerate R&D of PC VR headsets in US and Europe</i>.", link: "https://www.roadtovr.com/pimax-raises-13m-accelerate-r-d-pc-vr-headsets-us-europe/" }
    ]
};